# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscribeNum', models.IntegerField(default=0, verbose_name='订阅数')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('feedback', models.TextField(default='', verbose_name='反馈')),
                ('status', models.CharField(max_length=50, verbose_name='更新状况')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'db_table': 'learn',
                'ordering': ['c_time'],
            },
        ),
    ]
