# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='authorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Author', verbose_name='作者'),
        ),
    ]
