# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-12-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_learn_authorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('category', models.IntegerField(verbose_name='类别')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('quantity', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
                'ordering': ['id'],
            },
        ),
    ]
