# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-12-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.supplier'),
        ),
    ]
